apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: osamikoyo/poll-service:latest
        env:
        - name: DB_HOST
          value: "mariadb"
        - name: DB_USER
          value: "user"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: password
        - name: DB_NAME
          value: "testdb"
        - name: DB_PORT
          value: "3306"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: REDIS_HOST
          value: "redis"
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
