apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
type: Opaque
data:
  root-password: cm9vdHBhc3N3b3Jk  # echo -n "rootpassword" | base64
  password: cGFzc3dvcmQ=           # echo -n "password" | base64
