reqs:
  update_req_type : "request.vote.update"
  create_req_type : "request.vote.create"
rabbitmq_url : "amqp://rabbitmq:5672"
dsn : "/data/poll.db"
queue_name : "votes"
req_exchange : "requests"
out_exchange : "votes"
