version: '3.8'

services:
  poll_service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka 
    container_name: poll_service
    environment:
      - KAFKA_URL=kafka:9092
    volumes:
      - poll_data:/data
    networks:
      - kafka-network

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes 

networks:
  kafka-network:
    driver: bridge

volumes:
    poll_data:      

