services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    networks:
      - monitoring
  

  master-redis:
    image: redis:7.0-alpine
    container_name: master-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
      - MARIADB_DATABASE=testdb
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=no
      - MARIADB_RANDOM_ROOT_PASSWORD=no
      - MARIADB_ROOT_HOST=%
      - MARIADB_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - master-redis
      - prometheus
      - grafana
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=testdb
      - DB_PORT=3306

  rabbitmq:
    image: rabbitmq:3.12-management
    restart: unless-stopped
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # Web UI 
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  poll-data:  
  rabbitmq-data:  
  grafana-storage:
  redis-data:
  db_data:

