version: '3.8'

services:
  poll-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - APP_ENV=production
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - SQLITE_PATH=/data/poll.db  
    volumes:
      - poll-data:/data  

  rabbitmq:
    image: rabbitmq:3.12-management
    restart: unless-stopped
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # Web UI 
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  poll-data:  
  rabbitmq-data:  
